

# Base image to use, this must be set as the first line
FROM gabrielwu/nodejs:v0.01

# Maintainer: docker_user <docker_user at email.com> (@docker_user)
MAINTAINER gabrielwu yingpingwdz@163.com
USER root 
RUN npm install --global smart-npm --registry=https://registry.npm.taobao.org/

WORKDIR /usr/src/node
WORKDIR home
WORKDIR metinvest-site

#VOLUME 

# Commands to update the image


# Commands when creating a new container
#CMD [""]
