

# Base image to use, this must be set as the first line
FROM daocloud.io/library/node:0.10.28

# Maintainer: docker_user <docker_user at email.com> (@docker_user)
MAINTAINER gabrielwu yingpingwdz@163.com

EXPOSE 3000
EXPOSE 27017
EXPOSE 8000

# Commands to update the image


# Commands when creating a new container
#CMD [""]
